IMAGE_NAME = "centos/8"
ANSIBLE_NODES = 2

########################################################
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

##########################################################


  (1..ANSIBLE_NODES).each do |i|
    config.vm.define "ansible-node-#{i}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"
      node.vm.hostname = "ansible-node-#{i}"
      node.vm.provider :virtualbox do |vb|
        vb.name = "ansible-node-#{i}"
        vb.memory = 1024
        vb.cpus = 1
      end
      node.vm.provision :shell, path: "files/nodes-sshd.sh"
    end
  end

##########################################################


  config.vm.define "ansible-engine" do |ansible|
    ansible.vm.box = IMAGE_NAME
    ansible.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "intnet"
    ansible.vm.hostname = "ansible-engine1"
    ansible.vm.provider :virtualbox do |vb|
      vb.name ="ansible-engine1"
      vb.memory = 1024
      vb.cpus = 1
    end
    ansible.vm.provision :shell, path: "files/nodes-sshd.sh"
    ansible.vm.provision "ansible_local" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "/vagrant/files/engine-config.yaml"
      ansible.extra_vars = {
        node_ip: "192.168.50.11",
      }
    end
  end

###############################################################
end
