---

- hosts: all
  become: true

  vars:
    remote_user_name: vagrant

  tasks:
    - name: Copy sample inventory to Vagrant user home
      copy:
        src: '/vagrant/files/sample-inventory'
        dest: "/home/{{ remote_user_name}}/inventory"
        mode: '0755'
      when: inventory_hostname == 'ansible-engine1'

    - name: Install Packages
      yum:
        name:
          - git
          - vim
        state: present

    - name: Update /etc/hosts with node entries
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.50.11 ansible-engine
          192.168.50.21 ansible-node-1 node1
          192.168.50.22 ansible-node-2 node2
          192.168.50.23 ansible-node-2 node3
          192.168.50.24 ansible-node-2 node4
          192.168.50.25 ansible-node-2 node5
